var tableauQuestion = [
    {   question : "Comment vous devez vous possez sur l'Aéroport ?",
        propositionA : "Rapidement",
        propositionB : "Brutalement",
        propositionC : "En sens inverse",
        propositionD : "En douceur",
        reponse : "D"},
		
    {   question : "Vous décoller, Et vous apercevez un autres appareil, Que faite vous ?",
        propositionA : "Je décoller tant pis, pour le 2 éme appareil",
        propositionB : "Je ralenti, et j'attend qui décolle",
        propositionC : "J'essaye de décolle avant lui",
        propositionD : "Je reculer, j'attend qui décolle et puis ensuite je décolle",
        reponse : "D"},
		
    {   question : "Sans aucune indication : La vitesse au dessus d'une agglomération est de __ km/h",
        propositionA : "300",
        propositionB : "25",
        propositionC : "170",
        propositionD : "190",
        reponse : "C"},
	
	{   question : "Ou et quand pouvez sauter en parachute ?",
        propositionA : "Partout et quand je veut",
        propositionB : "Dans un secteur dégage et sécuriser",
        propositionC : "Au dessus d'une agglomération",
        propositionD : "Au dessus d'un océan",
        reponse : "B"},
		
	{   question : "Quel est le taux d'alcoolémie dans la conduite en état d'ébriété ?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "A"},
]
